version: "3.1"
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app:rw
    ports:
      - "9000:9000"
