version: "3.1"
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8888
    volumes:
      - .:/home/node/app:rw
    ports:
      - "8888:8888"
